# Generated by Django 4.2.13 on 2024-05-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_provider_id',
            new_name='delivery_provider',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_basket_id',
            new_name='order_basket',
        ),
        migrations.RenameField(
            model_name='orderbasket',
            old_name='shipping_provider_id',
            new_name='shipping_provider',
        ),
        migrations.AlterField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='orderbasket',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
